import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Tsender",
  description: "Generated by create next app",
};

export default function RootLayout(props: { children: React.ReactNode}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {props.children} {/* This is where the website code will be rendered */}
        </Providers>
      </body>
    </html>
  );
}
